# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='deal_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_author', to=settings.AUTH_USER_MODEL, verbose_name='当前处理人'),
        ),
        migrations.AlterField(
            model_name='content',
            name='level',
            field=models.IntegerField(choices=[(0, 'p0'), (1, 'p1'), (2, 'p2'), (3, 'p3'), (4, 'p4')], verbose_name='故障级别'),
        ),
        migrations.AlterField(
            model_name='zbxcontent',
            name='host',
            field=models.CharField(max_length=120, null=True, verbose_name='故障服务器Top10'),
        ),
        migrations.AlterField(
            model_name='zbxcontent',
            name='type',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='zbx应用集'),
        ),
    ]
